version: '3'
networks:
  zk-kafka-nw:
    external: false
services:
  zookeeper-sasl-1:
    image: confluentinc/cp-zookeeper:latest
    restart: on-failure:3
    hostname: zookeeper-sasl-1
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper-sasl-1:22888:23888;zookeeper-sasl-2:32888:33888;zookeeper-sasl-3:42888:43888
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/zookeeper_1_jaas.conf
        #-Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
    volumes:
      - ${KAFKA_SASL_SECRETS_DIR}:/etc/kafka/secrets
    networks:
      - zk-kafka-nw
    ports:
      - "22181:22181"

  zookeeper-sasl-2:
    image: confluentinc/cp-zookeeper:latest
    restart: on-failure:3
    hostname: zookeeper-sasl-2
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper-sasl-1:22888:23888;zookeeper-sasl-2:32888:33888;zookeeper-sasl-3:42888:43888
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/zookeeper_2_jaas.conf
        #-Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
    volumes:
      - ${KAFKA_SASL_SECRETS_DIR}:/etc/kafka/secrets
    networks:
      - zk-kafka-nw
    ports:
      - "32181:32181"

  zookeeper-sasl-3:
    image: confluentinc/cp-zookeeper:latest
    restart: on-failure:3
    hostname: zookeeper-sasl-3
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 42181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper-sasl-1:22888:23888;zookeeper-sasl-2:32888:33888;zookeeper-sasl-3:42888:43888
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/zookeeper_3_jaas.conf
        #-Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
    volumes:
      - ${KAFKA_SASL_SECRETS_DIR}:/etc/kafka/secrets
    networks:
      - zk-kafka-nw
    ports:
      - "42181:42181"

  kafka-sasl-1:
    image: confluentinc/cp-kafka:latest
    networks:
      - zk-kafka-nw
    restart: on-failure:3
    depends_on:
      - zookeeper-sasl-1
      - zookeeper-sasl-2
      - zookeeper-sasl-3
    ports:
      - "19092:19092"
    hostname: kafka-sasl-1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-sasl-1:22181,zookeeper-sasl-2:32181,zookeeper-sasl-3:42181
      KAFKA_ADVERTISED_LISTENERS: SASL_SSL://kafka-sasl-1:19092
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.broker1.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: broker1_keystore_creds
      KAFKA_SSL_KEY_CREDENTIALS: broker1_sslkey_creds
      KAFKA_SSL_CLIENT_AUTH: required
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: " "
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.broker1.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: broker1_truststore_creds
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SASL_SSL
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_LOG4J_ROOT_LOGLEVEL: DEBUG
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/broker1_jaas.conf
    volumes:
      - ${KAFKA_SASL_SECRETS_DIR}:/etc/kafka/secrets

  kafka-sasl-2:
    image: confluentinc/cp-kafka:latest
    networks:
      - zk-kafka-nw
    restart: on-failure:3
    depends_on:
      - zookeeper-sasl-1
      - zookeeper-sasl-2
      - zookeeper-sasl-3
    ports:
      - "29094:29094"
    hostname: kafka-sasl-2
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-sasl-1:22181,zookeeper-sasl-2:32181,zookeeper-sasl-3:42181
      KAFKA_ADVERTISED_LISTENERS: SASL_SSL://kafka-sasl-2:29094
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.broker2.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: broker2_keystore_creds
      KAFKA_SSL_KEY_CREDENTIALS: broker2_sslkey_creds
      KAFKA_SSL_CLIENT_AUTH: required
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: " "
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.broker2.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: broker2_truststore_creds
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SASL_SSL
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_LOG4J_ROOT_LOGLEVEL: DEBUG
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/broker2_jaas.conf
    volumes:
      - ${KAFKA_SASL_SECRETS_DIR}:/etc/kafka/secrets

  kafka-sasl-3:
    image: confluentinc/cp-kafka:latest
    networks:
      - zk-kafka-nw
    restart: on-failure:3
    depends_on:
      - zookeeper-sasl-1
      - zookeeper-sasl-2
      - zookeeper-sasl-3
    ports:
      - "39094:39094"
    hostname: kafka-sasl-3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-sasl-1:22181,zookeeper-sasl-2:32181,zookeeper-sasl-3:42181
      KAFKA_ADVERTISED_LISTENERS: SASL_SSL://kafka-sasl-3:39094
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.broker3.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: broker3_keystore_creds
      KAFKA_SSL_KEY_CREDENTIALS: broker3_sslkey_creds
      KAFKA_SSL_CLIENT_AUTH: required
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: " "
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.broker3.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: broker3_truststore_creds
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SASL_SSL
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_LOG4J_ROOT_LOGLEVEL: DEBUG
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/broker3_jaas.conf
    volumes:
      - ${KAFKA_SASL_SECRETS_DIR}:/etc/kafka/secrets
